### ISSUE TITLE
[FEAT]Reasoning 기반의 prompt를 형성한 실험

### ISSUE THREAD

**Issue by someDeveloperDH** [boostcampaitech7/level2-nlp-generationfornlp-nlp-10-lv3#14]
## Feature Overview
- 다양한 리즈닝 기법을 통하여 프롬프트를 작성.
- 목적 : 지문과 질문의 관계를 잘 추론할 수 있도록 함.

## Task
- [x] 귀납적 리즈닝 : 지문 기반 질문에 관한 사례 만들어 풀기.
- [x] 연역적 리즈닝 : 대전제와 소전제 기반 문제풀기.
- [x] 의사결정 리즈닝 : 단계적 풀이법 제공.

## Reference (Option)
-
