### ISSUE TITLE
[FEAT] Collect & Process Click Dataset

### ISSUE THREAD

**Issue by K-yng** [boostcampaitech7/level2-nlp-generationfornlp-nlp-10-lv3#18]
## Feature Overview
- Click dataset 수집 및 전처리
- 데이터 정제
- 데이터 format 수정
- 기타 필요한 처리 등

## Task
- [x] Data Loading 및 적절한 formatting
- [x] 정제 필요한 항목 정의 및 수행
- [x] question에 paragraph 함께 들어 있는 경우 정의 및 split
- [x] 추가적으로 필요한 task 정의
