### ISSUE TITLE
[FEAT] Orca 기반의 reasoning dataset 생성 및 모델 fine-tuning

### ISSUE THREAD

**Issue by K-yng** [boostcampaitech7/level2-nlp-generationfornlp-nlp-10-lv3#24]
## Feature Overview
- Orca: Progressive Learning from Complex  Explanation Traces of GPT-4 의 내용을 기반으로 reasoning 데이터 생성
- LLM의 model behavior를 reasoning data에 대한 fine-tuning을 통해 소규모 모델에 학습

## Task
- [x] 논문에 제시된 몇 가지 system prompt를 활용해 reasoning 생성
- [x] 해당 reasoning을 기반으로 fine-tuning 및 성능 test
- [x] 성능 개선 확인 후, 여러 system prompt를 활용한 다양한 resoning에 대해 학습 시행

## Reference (Option)
- Orca: Progressive Learning from Complex  Explanation Traces of GPT-4
