### ISSUE TITLE
[FEAT] generation based inference with self-consistency

### ISSUE THREAD

**Issue by K-yng** [boostcampaitech7/level2-nlp-generationfornlp-nlp-10-lv3#31]
## Feature Overview
- generation 기반의 inference 모델링
- repeatition & voting을 활용한 self-consistency method 적용

## Task
- [x] model pipline 생성
- [x] chat template 설정
- [x] self-consistency 적용

## Reference (Option)
- https://arxiv.org/abs/2203.11171
