### ISSUE TITLE
[REFACTOR] CLIcK dataset loader refactoring

### ISSUE THREAD

**Issue by K-yng** [boostcampaitech7/level2-nlp-generationfornlp-nlp-10-lv3#33]
## Feature Overview
- click dataset loader에 너무 많은 기능이 구현돼 있음
- 해당 기능들을 재구조화하는 과정 필요

## Task
- [x] text split 함수 utils로 옮기기
- [x] split process도 함수화
- [x] tag 기준 인덱싱 함수화

## Reference (Option)
-
